# -*- coding: utf-8 -*-
"""Feature Engineering/Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbEjSLexgGCCyx08n8SS8syfD8j-Fylo
"""

import numpy as np

vector = np.array([2, 4, 6, 8, 10])
mean = np.mean(vector)
sample_variance = np.var(vector, ddof=1)

print(f"Mean of the vector: {mean}")
print(f"Sample Variance of the vector: {sample_variance}")

import numpy as np

vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([2, 4, 6, 8, 10])
covariance = np.cov(vector1, vector2)[0][1]

print(f"Covariance between vector1 and vector2: {covariance}")

import numpy as np

vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([2, 4, 6, 8, 10])
correlation = np.corrcoef(vector1, vector2)[0][1]

print(f"Correlation between vector1 and vector2: {correlation}")

import numpy as np

def compute_covariance_correlation_matrix(X):
    covariance_matrix = np.cov(X, rowvar=False)
    correlation_matrix = np.corrcoef(X, rowvar=False)
    return covariance_matrix, correlation_matrix

if __name__ == "__main__":
    X = np.array([
        [1.0, 2.0, 3.0, 4.0, 5.0],
        [5.0, 4.0, 3.0, 2.0, 1.0],
        [2.0, 3.0, 4.0, 5.0, 6.0]
    ])

    covariance_matrix, correlation_matrix = compute_covariance_correlation_matrix(X)

    print("Covariance Matrix:")
    print(covariance_matrix)

    print("\nCorrelation Matrix:")
    print(correlation_matrix)